#!/bin/bash

sed "s/\?//g" | #deletes and replaces desired chars
sed "s/\`/\'/g" |
sed "s/\-/\ /g" |
sed "s/<u>//g" |
sed "s/<\/u>//g" |

grep -iE "\ *<td[^>]*>[pkmnwlhaeiou\'\ ]{1,}<\/td>\ *" | #extract hwn word line

sed 's/<td[^>]*>//g'  | #anything inside td <> gets deleted
sed 's/<\/td>//g' | #deletes </td>
tr -s '\ ' '\n' |  #squeeze spaces into newlines
tr '[:upper:]' '[:lower:]' | #makea everything lowercase
sort -u;  #sort/remove duplicates
